name: ustreamer

on:
  push:
    branches: 
      - master
    paths:
      - ustreamer/**
      - .github/workflows/ustreamer.yml
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

env:
  BUILD_VERSION: "git"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }} 

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604
        with:
          egress-policy: audit

      - name: Source checkout
        uses: actions/checkout@v3
 
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REPOSITORY }}
          tags: |
            type=sha,format=long,prefix=sha256:
          labels: |
            org.opencontainers.image.version=${{ env.BUILD_VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=${{ env.REPOSITORY }}

      - name: GitHub login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: DockerHub login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: push-step
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ${{ github.workflow }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            BUILD_VERSION
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}, mode=max
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            docker.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
            docker.io/${{ env.REPOSITORY }}:latest
            ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
            ghcr.io/${{ env.REPOSITORY }}:latest

      # The following is for testing container signing and generating SBOMs
      # Workaround for buildx bug: https://github.com/docker/build-push-action/issues/461
      #
      # Links
      # https://githubhelp.com/chrisns/cosign-keyless-demo
      # https://blog.chainguard.dev/zero-friction-keyless-signing-with-github-actions/
      # https://github.com/mattmoor/zero-friction-actions/blob/main/.github/workflows/docker-publish.yml
      # https://github.com/docker/roadmap/issues/269
      # https://github.com/anchore/syft

      - name: Install cosign
        uses: sigstore/cosign-installer@v2

      - name: Install syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Sign the image digest and generate SBOM
        run: |
          cosign sign docker.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }}
          syft docker.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }} -o json > docker_sbom.json
          cosign attest --predicate docker_sbom.json docker.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }}
          cosign sign ghcr.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }}
          syft ghcr.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }} -o json > ghcr_sbom.json
          cosign attest --predicate ghcr_sbom.json ghcr.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: 1


      #- name: Verify the image digest and SBOM
      #  run: |
      #    cosign verify docker.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }}
      #    cosign verify-attestation docker.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }}
      #    syft attest -o syft-json docker.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }}
      #    cosign verify ghcr.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }}
      #    cosign verify-attestation ghcr.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }}
      #    syft attest -o syft-json ghcr.io/${{ env.REPOSITORY }}@${{ steps.push-step.outputs.digest }}
      #  env:
      #    COSIGN_EXPERIMENTAL: 1